### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by cpappzoro** [husaynhakeem/Products-Android-Architecture-Components#1]
2019-03-16 20:58:17.479 31080-31095/io.husaynhakeem.products_android_architecture_components_sample E/AndroidRuntime: FATAL EXCEPTION: pool-1-thread-1
    Process: io.husaynhakeem.products_android_architecture_components_sample, PID: 31080
    android.database.sqlite.SQLiteConstraintException: NOT NULL constraint failed: Product.name (code 1299)
    #################################################################
    Error Code : 1299 (SQLITE_CONSTRAINT_NOTNULL)
    Caused By : Abort due to constraint violation.
    	(NOT NULL constraint failed: Product.name (code 1299))
    #################################################################
        at android.database.sqlite.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
        at android.database.sqlite.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:862)
        at android.database.sqlite.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:788)
        at android.database.sqlite.SQLiteStatement.executeInsert(SQLiteStatement.java:86)
        at android.arch.persistence.db.framework.FrameworkSQLiteStatement.executeInsert(FrameworkSQLiteStatement.java:50)
        at android.arch.persistence.room.EntityInsertionAdapter.insert(EntityInsertionAdapter.java:80)
        at io.husaynhakeem.products_android_architecture_components_sample.repository.local.ProductsDao_Impl.saveProducts(ProductsDao_Impl.java:75)
        at io.husaynhakeem.products_android_architecture_components_sample.repository.local.LocalRepository.saveProducts(LocalRepository.kt:9)
        at io.husaynhakeem.products_android_architecture_components_sample.repository.ProductsRepository$refreshProducts$1.run(ProductsRepository.kt:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)

**Comment by husaynhakeem** [comment]
@cpappzoro Issue was fixed.
